# Copyright 2019 Google LLC.
# Modifications Copyright 2024 deepvariant-linux-arm64 contributors.
#
# ARM64 build of the DeepTrio release Docker image.
# Uses pre-built ARM64 builder from ghcr.io (~10min build).
#
# Build:
#   docker build -f Dockerfile.deeptrio --platform linux/arm64 -t deeptrio-arm64 .
#
# Full from-source (build builder first):
#   docker build -f docker/Dockerfile.arm64.builder -t dv-builder .
#   docker build -f Dockerfile.deeptrio --build-arg BUILDER_IMAGE=dv-builder --platform linux/arm64 -t deeptrio-arm64 .

ARG BUILDER_IMAGE=ghcr.io/lambda-biolab/deepvariant-linux-arm64:base-builder-v1.9.0
ARG FROM_IMAGE=arm64v8/ubuntu:24.04
ARG VERSION_DEEPTRIO=1.9.0

# --- Stage 1: pre-built Bazel binaries ---------------------------------------
FROM ${BUILDER_IMAGE} AS builder

# --- Stage 2: runtime --------------------------------------------------------
FROM ${FROM_IMAGE}
ARG VERSION_DEEPTRIO
ENV VERSION_DEEPTRIO=${VERSION_DEEPTRIO}
ENV PATH="$PATH:/opt/deepvariant/bin"
COPY --from=ghcr.io/astral-sh/uv:0.10.9 /uv /usr/local/bin/uv

RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
        samtools bcftools parallel libjemalloc2 wget \
        gcc pkg-config zlib1g-dev curl git unzip \
        libssl-dev libcurl4-openssl-dev liblz-dev libbz2-dev liblzma-dev \
        libboost-graph-dev && \
    apt-get clean autoclean && \
    apt-get autoremove -y --purge && \
    rm -rf /var/lib/apt/lists/*

RUN uv venv /opt/venv --python 3.10 && \
    ln -sf /opt/venv/bin/python3 /usr/bin/python3 && \
    ln -sf /opt/venv/bin/python3 /usr/bin/python
ENV VIRTUAL_ENV=/opt/venv
ENV PATH="/opt/venv/bin:$PATH"

WORKDIR /opt/
COPY --from=builder /opt/deepvariant/bazel-bin/licenses.zip .

WORKDIR /opt/deepvariant/bin/
COPY --from=builder /opt/deepvariant/scripts/build/run-prereq.sh .
COPY --from=builder /opt/deepvariant/scripts/build/settings.sh .
COPY --from=builder /opt/deepvariant/scripts/build/settings_arm64.sh .
COPY --from=builder /opt/deepvariant/bazel-out/aarch64-opt/bin/deepvariant/call_variants.zip .
COPY --from=builder /opt/deepvariant/bazel-out/aarch64-opt/bin/deepvariant/postprocess_variants.zip .
COPY --from=builder /opt/deepvariant/bazel-out/aarch64-opt/bin/deepvariant/vcf_stats_report.zip .
COPY --from=builder /opt/deepvariant/bazel-out/aarch64-opt/bin/deepvariant/show_examples.zip .
COPY --from=builder /opt/deepvariant/bazel-out/aarch64-opt/bin/deepvariant/runtime_by_region_vis.zip .
COPY --from=builder /opt/deepvariant/scripts/run_deeptrio.py ./deeptrio/
COPY --from=builder /opt/deepvariant/bazel-out/aarch64-opt/bin/deeptrio/make_examples.zip ./deeptrio/
RUN ./run-prereq.sh && \
    uv pip install --no-cache \
        --reinstall-package cryptography --reinstall-package cffi \
        cryptography cffi "httplib2<0.22" absl-py==0.13.0 onnxruntime onnx && \
    uv pip install --no-cache etils && \
    python3 -c "import etils, onnxruntime; print(f'OK: etils {etils.__version__}, ort {onnxruntime.__version__}')"

RUN apt-get purge -y --auto-remove \
        gcc cpp pkg-config git curl \
        zlib1g-dev libssl-dev libcurl4-openssl-dev \
        liblz-dev libbz2-dev liblzma-dev libboost-graph-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Create shell wrappers for python zip files for easier use.
RUN \
  BASH_HEADER='#!/bin/bash' && \
  printf "%s\n%s\n" "${BASH_HEADER}" 'python3 /opt/deepvariant/bin/deeptrio/make_examples.zip "$@"' > /opt/deepvariant/bin/deeptrio/make_examples && \
  printf "%s\n%s\n" "${BASH_HEADER}" 'python3 /opt/deepvariant/bin/call_variants.zip "$@"' > /opt/deepvariant/bin/call_variants && \
  printf "%s\n%s\n" "${BASH_HEADER}" 'python3 /opt/deepvariant/bin/postprocess_variants.zip "$@"' > /opt/deepvariant/bin/postprocess_variants && \
  printf "%s\n%s\n" "${BASH_HEADER}" 'python3 /opt/deepvariant/bin/vcf_stats_report.zip "$@"' > /opt/deepvariant/bin/vcf_stats_report && \
  printf "%s\n%s\n" "${BASH_HEADER}" 'python3 /opt/deepvariant/bin/show_examples.zip "$@"' > /opt/deepvariant/bin/show_examples && \
  printf "%s\n%s\n" "${BASH_HEADER}" 'python3 /opt/deepvariant/bin/runtime_by_region_vis.zip "$@"' > /opt/deepvariant/bin/runtime_by_region_vis && \
  printf "%s\n%s\n" "${BASH_HEADER}" 'python3 -u /opt/deepvariant/bin/deeptrio/run_deeptrio.py "$@"' > /opt/deepvariant/bin/deeptrio/run_deeptrio && \
  chmod +x /opt/deepvariant/bin/deeptrio/make_examples \
    /opt/deepvariant/bin/call_variants \
    /opt/deepvariant/bin/postprocess_variants \
    /opt/deepvariant/bin/vcf_stats_report \
    /opt/deepvariant/bin/show_examples \
    /opt/deepvariant/bin/runtime_by_region_vis \
    /opt/deepvariant/bin/deeptrio/run_deeptrio

# Copy models
WORKDIR /opt/models/deeptrio/wgs/child
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wgs_child.savedmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wgs_child.savedmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wgs_child.savedmodel/example_info.json ./
WORKDIR /opt/models/deeptrio/wgs/child/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wgs_child.savedmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wgs_child.savedmodel/variables/variables.index ./
RUN chmod -R +r /opt/models/deeptrio/wgs/child/*

WORKDIR /opt/models/deeptrio/wgs/parent
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wgs_parent.savedmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wgs_parent.savedmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wgs_parent.savedmodel/example_info.json ./
WORKDIR /opt/models/deeptrio/wgs/parent/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wgs_parent.savedmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wgs_parent.savedmodel/variables/variables.index ./
RUN chmod -R +r /opt/models/deeptrio/wgs/parent/*

WORKDIR /opt/models/deeptrio/pacbio/child
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.pacbio_child.savedmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.pacbio_child.savedmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.pacbio_child.savedmodel/example_info.json ./
WORKDIR /opt/models/deeptrio/pacbio/child/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.pacbio_child.savedmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.pacbio_child.savedmodel/variables/variables.index ./
RUN chmod -R +r /opt/models/deeptrio/pacbio/child/*

WORKDIR /opt/models/deeptrio/pacbio/parent
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.pacbio_parent.savedmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.pacbio_parent.savedmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.pacbio_parent.savedmodel/example_info.json ./
WORKDIR /opt/models/deeptrio/pacbio/parent/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.pacbio_parent.savedmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.pacbio_parent.savedmodel/variables/variables.index ./
RUN chmod -R +r /opt/models/deeptrio/pacbio/parent/*

WORKDIR /opt/models/deeptrio/wes/child
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wes_child.savedmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wes_child.savedmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wes_child.savedmodel/example_info.json ./
WORKDIR /opt/models/deeptrio/wes/child/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wes_child.savedmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wes_child.savedmodel/variables/variables.index ./
RUN chmod -R +r /opt/models/deeptrio/wes/child/*

WORKDIR /opt/models/deeptrio/wes/parent
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wes_parent.savedmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wes_parent.savedmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wes_parent.savedmodel/example_info.json ./
WORKDIR /opt/models/deeptrio/wes/parent/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wes_parent.savedmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.wes_parent.savedmodel/variables/variables.index ./
RUN chmod -R +r /opt/models/deeptrio/wes/parent/*

WORKDIR /opt/models/deeptrio/ont/child
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.ont_child.savedmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.ont_child.savedmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.ont_child.savedmodel/example_info.json ./
WORKDIR /opt/models/deeptrio/ont/child/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.ont_child.savedmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.ont_child.savedmodel/variables/variables.index ./
RUN chmod -R +r /opt/models/deeptrio/ont/child/*

WORKDIR /opt/models/deeptrio/ont/parent
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.ont_parent.savedmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.ont_parent.savedmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.ont_parent.savedmodel/example_info.json ./
WORKDIR /opt/models/deeptrio/ont/parent/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.ont_parent.savedmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/savedmodels/deeptrio.ont_parent.savedmodel/variables/variables.index ./
RUN chmod -R +r /opt/models/deeptrio/ont/parent/*

# Copy small model checkpoints
WORKDIR /opt/smallmodels/deeptrio/wgs/child
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.wgs_child.smallmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.wgs_child.smallmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.wgs_child.smallmodel/keras_metadata.pb ./
WORKDIR /opt/smallmodels/deeptrio/wgs/child/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.wgs_child.smallmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.wgs_child.smallmodel/variables/variables.index ./
RUN chmod -R +r /opt/smallmodels/deeptrio/wgs/child/*


WORKDIR /opt/smallmodels/deeptrio/wgs/parent
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.wgs_parent.smallmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.wgs_parent.smallmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.wgs_parent.smallmodel/keras_metadata.pb ./
WORKDIR /opt/smallmodels/deeptrio/wgs/parent/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.wgs_parent.smallmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.wgs_parent.smallmodel/variables/variables.index ./
RUN chmod -R +r /opt/smallmodels/deeptrio/wgs/parent/*

WORKDIR /opt/smallmodels/deeptrio/pacbio/child
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.pacbio_child.smallmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.pacbio_child.smallmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.pacbio_child.smallmodel/keras_metadata.pb ./
WORKDIR /opt/smallmodels/deeptrio/pacbio/child/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.pacbio_child.smallmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.pacbio_child.smallmodel/variables/variables.index ./
RUN chmod -R +r /opt/smallmodels/deeptrio/pacbio/child/*

WORKDIR /opt/smallmodels/deeptrio/pacbio/parent
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.pacbio_parent.smallmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.pacbio_parent.smallmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.pacbio_parent.smallmodel/keras_metadata.pb ./
WORKDIR /opt/smallmodels/deeptrio/pacbio/parent/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.pacbio_parent.smallmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.pacbio_parent.smallmodel/variables/variables.index ./
RUN chmod -R +r /opt/smallmodels/deeptrio/pacbio/parent/*

WORKDIR /opt/smallmodels/deeptrio/ont/child
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.ont_child.smallmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.ont_child.smallmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.ont_child.smallmodel/keras_metadata.pb ./
WORKDIR /opt/smallmodels/deeptrio/ont/child/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.ont_child.smallmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.ont_child.smallmodel/variables/variables.index ./
RUN chmod -R +r /opt/smallmodels/deeptrio/ont/child/*

WORKDIR /opt/smallmodels/deeptrio/ont/parent
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.ont_parent.smallmodel/fingerprint.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.ont_parent.smallmodel/saved_model.pb \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.ont_parent.smallmodel/keras_metadata.pb ./
WORKDIR /opt/smallmodels/deeptrio/ont/parent/variables
ADD https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.ont_parent.smallmodel/variables/variables.data-00000-of-00001 \
  https://storage.googleapis.com/deepvariant/models/DeepTrio/${VERSION_DEEPTRIO}/smallmodels/deeptrio.ont_parent.smallmodel/variables/variables.index ./
RUN chmod -R +r /opt/smallmodels/deeptrio/ont/parent/*



# Reason: docker_entrypoint.sh auto-detects BF16, AmpereOne SIGILL guard,
# jemalloc, OMP threads — critical for cross-platform ARM64 correctness.
COPY scripts/docker_entrypoint.sh /opt/deepvariant/bin/docker_entrypoint.sh
COPY scripts/autoconfig.sh /opt/deepvariant/scripts/autoconfig.sh
RUN chmod +x /opt/deepvariant/bin/docker_entrypoint.sh \
             /opt/deepvariant/scripts/autoconfig.sh

ENV PATH="${PATH}:/opt/deepvariant/bin/deeptrio:/opt/deepvariant/bin"
ENV PYTHONPATH="/opt/venv/lib/python3.10/site-packages"

WORKDIR /opt/deepvariant

ENTRYPOINT ["/opt/deepvariant/bin/docker_entrypoint.sh"]
CMD ["/opt/deepvariant/bin/deeptrio/run_deeptrio", "--help"]
